version: 1
accounts:
  - name: alice
    coins: ["20000000blu"]
  - name: bob
    coins: ["10000blu"]
  - name: governor
    coins: ["1000000000blu"]
    mnemonic: such crisp stereo famous mixed horror journey host tell model swarm goddess
validators:
  - name: alice
    bonded: "10000000blu"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "ublu"